favorite_movie = input("What's your favorite movie?")
print(favorite_movie)
favorite_number1 = input("What's your first favorite number?")
favorite_number2 = input("What's your second favorite number?")
end_favorite_number = int(favorite_number1) + int(favorite_number2)
print("Your favorite numbers added is: ", end_favorite_number)
pet_name = input("What's your pet's name?")
pet_favorite_toy = input("What's your pet's favorite toy?")
print(f"{pet_name}'s favorite toy is {pet_favorite_toy}")
